name = "www"
main = "./.output/server/index.mjs"
compatibility_date = "2022-09-10"
route = "www.gravitalia.com"

rules = [
    { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

[site]
bucket = ".output/public"

[observability]
enabled = false